name: Slack Notify
on:
  workflow_call:
    inputs:
      webhook:
        description: "The Slack webhook URL to send the notification to"
        required: true
        type: string
      stage:
        description: "The status of the build (e.g., Success, Failure)"
        required: true
        type: string
      title:
        description: "The title of the Slack message"
        required: false
        type: string
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notify to Slack
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ inputs.webhook }}
          webhook-type: incoming-webhook
          payload: |
            {
                "text": "${{ inputs.title }}"
            }
